POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Holly McClane",
    "ssn": "123abc",
    "dateOfBirth": "1971-01-041",
    "occupation": "Housewife",
    "gender": "female"
}